# Allow Yarn to modify the lockfile during installation
immutableInstalls: false

# Use node_modules linker for compatibility
nodeLinker: node-modules

# Enable plugins
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

# Ensure peer dependencies are properly resolved
enabledFalsePositives:
  - YN0002 # Peer dependency warnings